#mysql connection details
spring:
  application:
    name: LearningProject
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/eazybank
    username: root
    password: 12345
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:ERROR}
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
server:
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:10m}